#!/bin/bash

arm-none-linux-gnueabi-g++ -c mot.c -pthread -o mot.o
arm-none-linux-gnueabi-g++ -c motorboard.c -pthread -o motorboard.o
arm-none-linux-gnueabi-g++ -c util.c -pthread -o util.o
arm-none-linux-gnueabi-g++ -c gpio.c -pthread -o gpio.o

